"""
NeuroLearn AI — In-Memory Data Store
Simulates a database without requiring MongoDB for the MVP.
Stores users, question attempts, and analytics data.
"""
from datetime import datetime
from typing import Dict, List, Optional
import uuid


# ─── In-memory fallback stores ────────────────────────────────────────────────────────

users_db: Dict[str, dict] = {}          # email -> user dict
attempts_db: List[dict] = []            # list of all question attempts
study_plans_db: List[dict] = []         # list of all study plans (append-only)
user_skills_db: List[dict] = []         # list of all skill trackers
sessions_db: Dict[str, dict] = {}       # token -> user

# Import Mongo Connection Manager
try:
    from models.mongo import mongodb_available, get_db
except ImportError:
    mongodb_available = False
    get_db = lambda: None


# ─── Seed data ───────────────────────────────────────────────────────────────



# ─── Helpers ─────────────────────────────────────────────────────────────────

def update_user_xp(user_id: str, xp_delta: int) -> int:
    if mongodb_available:
        try:
            result = get_db().users.find_one_and_update(
                {"id": user_id},
                {"$inc": {"xp": xp_delta}},
                return_document=True,
                projection={"_id": 0}
            )
            if result:
                return result.get("xp", 0)
        except:
            pass
    for u in users_db.values():
        if u["id"] == user_id:
            u["xp"] = u.get("xp", 0) + xp_delta
            return u["xp"]
    return 0

def get_user_by_email(email: str) -> Optional[dict]:
    if mongodb_available:
        try:
            user = get_db().users.find_one({"email": email}, {"_id": 0})
            if user: return user
        except: pass
    return users_db.get(email)

def get_user_by_id(user_id: str) -> Optional[dict]:
    if mongodb_available:
        try:
            user = get_db().users.find_one({"id": user_id}, {"_id": 0})
            if user: return user
        except: pass
    for u in users_db.values():
        if u["id"] == user_id:
            return u
    return None

def create_user(name: str, email: str, hashed_password: str, exam: str) -> dict:
    user = {
        "id": str(uuid.uuid4()),
        "name": name,
        "email": email,
        "hashed_password": hashed_password,
        "exam": exam,
        "xp": 0,
        "streak": 0,
        "level": 1,
        "created_at": datetime.utcnow().isoformat(),
    }
    
    if mongodb_available:
        try:
            get_db().users.insert_one(user.copy())
        except: pass
        
    users_db[email] = user
    return user

def record_attempt(attempt: dict):
    if mongodb_available:
        try:
            get_db().attempts.insert_one(attempt.copy())
        except: pass
    attempts_db.append(attempt)

def get_user_attempts(user_id: str) -> List[dict]:
    if mongodb_available:
        try:
            return list(get_db().attempts.find({"user_id": user_id}, {"_id": 0}))
        except: pass
    return [a for a in attempts_db if a.get("user_id") == user_id]

def save_study_plan(user_id: str, plan_data: dict):
    plan_data["user_id"] = user_id
    if mongodb_available:
        try:
            get_db().study_plans.insert_one(plan_data.copy())
        except: pass
    study_plans_db.append(plan_data)

def get_study_plan(user_id: str) -> Optional[dict]:
    """Returns the most recently generated study plan for the user."""
    if mongodb_available:
        try:
            # Sort by created_at descending to get the newest
            p = get_db().study_plans.find_one(
                {"user_id": user_id}, 
                {"_id": 0},
                sort=[("created_at", -1)]
            )
            if p: return p
        except: pass
    
    # Fallback: get newest from in-memory list
    user_plans = [p for p in study_plans_db if p.get("user_id") == user_id]
    if user_plans:
        return sorted(user_plans, key=lambda x: x.get("created_at", ""), reverse=True)[0]
    return None

def get_study_plans_history(user_id: str) -> List[dict]:
    """Returns all study plans generated by the user, newest first."""
    if mongodb_available:
        try:
            cursor = get_db().study_plans.find({"user_id": user_id}, {"_id": 0}).sort("created_at", -1)
            return list(cursor)
        except: pass
        
    user_plans = [p for p in study_plans_db if p.get("user_id") == user_id]
    return sorted(user_plans, key=lambda x: x.get("created_at", ""), reverse=True)


# ─── Skill Tracking ──────────────────────────────────────────────────────────

def calculate_skill_level(correct_count: int, total_attempts: int) -> str:
    """Calculates skill tier dynamically based on win-rate threshold."""
    if total_attempts < 3:
        return "Medium" # Not enough data, default to standard tier
    ratio = correct_count / total_attempts
    if ratio < 0.4:
        return "Weak"
    elif ratio > 0.75:
        return "Strong"
    return "Medium"

def update_skill_on_attempt(user_id: str, subject: str, topic: str, correct: bool) -> str:
    """Updates MongoDB / In-memory skill stats and returns the new skill level."""
    skill_doc = None
    
    if mongodb_available:
        try:
            skill_doc = get_db().user_skills.find_one({"user_id": user_id, "subject": subject, "topic": topic})
            if skill_doc:
                new_total = skill_doc.get("total_attempts", 0) + 1
                new_correct = skill_doc.get("correct_count", 0) + (1 if correct else 0)
                new_level = calculate_skill_level(new_correct, new_total)
                
                get_db().user_skills.update_one(
                    {"_id": skill_doc["_id"]},
                    {"$set": {
                        "total_attempts": new_total,
                        "correct_count": new_correct,
                        "skill_level": new_level
                    }}
                )
                return new_level
            else:
                new_level = calculate_skill_level(1 if correct else 0, 1)
                get_db().user_skills.insert_one({
                    "user_id": user_id,
                    "subject": subject,
                    "topic": topic,
                    "total_attempts": 1,
                    "correct_count": 1 if correct else 0,
                    "skill_level": new_level
                })
                return new_level
        except: pass
        
    # Fallback to Memory
    found = next((s for s in user_skills_db if s["user_id"] == user_id and s["topic"] == topic), None)
    if found:
        found["total_attempts"] += 1
        found["correct_count"] += (1 if correct else 0)
        found["skill_level"] = calculate_skill_level(found["correct_count"], found["total_attempts"])
        return found["skill_level"]
    else:
        new_level = calculate_skill_level(1 if correct else 0, 1)
        user_skills_db.append({
            "user_id": user_id,
            "subject": subject,
            "topic": topic,
            "total_attempts": 1,
            "correct_count": 1 if correct else 0,
            "skill_level": new_level
        })
        return new_level

def get_weakest_topic(user_id: str, active_subject: Optional[str] = None) -> Optional[dict]:
    """Finds the topic the user struggles with the most."""
    skills = []
    if mongodb_available:
        try:
            query = {"user_id": user_id}
            if active_subject:
                query["subject"] = active_subject
            skills = list(get_db().user_skills.find(query, {"_id": 0}))
        except: pass
    
    if not skills:
        user_skills = [s for s in user_skills_db if s["user_id"] == user_id]
        if active_subject:
            user_skills = [s for s in user_skills if s["subject"].lower() == active_subject.lower()]
        skills = user_skills

    if not skills:
        return None
        
    # Sort finding the minimal correctness ratio. Minimum 3 attempts for statistical validity.
    valid_skills = [s for s in skills if s.get("total_attempts", 0) >= 3]
    if valid_skills:
        return min(valid_skills, key=lambda s: s.get("correct_count", 0) / max(1, s.get("total_attempts", 1)))
        
    # If no topic has 3 attempts, return the one with lowest raw win-rate
    return min(skills, key=lambda s: s.get("correct_count", 0) / max(1, s.get("total_attempts", 1)))
